pool:
    name: Azure Pipelines

trigger:
- "*"

pr:
- "*"

resources:
  repositories:
  - repository: ReusablePipelines
    type: git
    name: Organization/pipelineRetain
    ref: main

stages:
  - stage: "node_dependecies"
    jobs:
    - template: install_node_dependency_stage.yml@ReusablePipelines

  - stage: "unit_tests"
    dependsOn: "node_dependecies"
    jobs:
    - job: RunUnitTests
      variables:
        mustInstallDependencies: $[ stageDependencies.node_dependecies.CheckIfNoTaggedPipelineExists.outputs['check_for_tagged_pipeline.mustInstallDependencies'] ]

      steps:
      - template: download_node_dependencies_step.yml@ReusablePipelines
      - task: CmdLine@2
        inputs:
          displayName: "Unit tests"
          script: |
              cd $(Build.SourcesDirectory)
              mkdir -p tests/unit/coverage
              chmod -R 777 node_modules
              npm run ci:test:coverage

        continueOnError: true
        condition: always()

      - task: PublishCodeCoverageResults@1
        inputs:
          displayName: "Publish code coverage report within Azure DevOps"
          workingDirectory: "$(Build.SourcesDirectory)"
          codeCoverageTool: Cobertura
          summaryFileLocation: tests/unit/coverage/cobertura-coverage.xml